"""The state Stage 3 renders, and the six fixtures that demonstrate each one.

## Why a third vocabulary

Stage 1 owns ``coverageStatus``. The engine owns ``researchStatus``. Neither
alone answers the question a renderer actually has, which is *what do I draw*.
"Suspended" and "stale" are facts about coverage and freshness; "model under
validation" is a fact about the model; "partial" is a fact about the inputs.
A UI that had to combine three vocabularies in a template would combine them
slightly differently on every screen.

So :class:`~engine.goh_dip_tong.contracts.enums.UiState` is derived here, in
one function, in a fixed precedence, and written into every snapshot. Exactly
one state applies to any document, and the mapping is a thing you can read
rather than a condition scattered through markup.

## The fixtures

Six documents, one per state, under ``fixtures/ui_states/``. They are **real
engine output**, not hand-written JSON — generated by running the engine over
controlled mutations of the synthetic bank, so a fixture cannot drift away from
what the engine actually produces. ``test_ui_states.py`` regenerates all six and
compares byte for byte.

Every ticker is synthetic. ``FULL_RESEARCH`` is ``SYNB`` and the other five are
``SYN*`` variants, so no real issuer appears in a fixture that carries a
valuation — or in one that does not, which keeps the rule simple enough to
enforce mechanically.
"""

from __future__ import annotations

import copy
import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

from pipeline.goh_dip_tong.settings import Settings as PipelineSettings

from ..contracts.enums import RefusalReason, ResearchStatus, UiState
from ..settings import EngineSettings

#: Refusal reasons that mean *the data is short*, as distinct from *the model
#: is not validated*. The split is the whole difference between PARTIAL and
#: MODEL_UNDER_VALIDATION, and it is the difference a reader cares about:
#: one is waiting on collection, the other on methodology.
DATA_SHORTFALL_REASONS = frozenset({
    str(RefusalReason.INSUFFICIENT_INPUTS),
    str(RefusalReason.INSUFFICIENT_HISTORY),
    str(RefusalReason.NO_MARKET_DATA),
})


def derive(
    coverage_status: Optional[str],
    research_status: str,
    model_family: Optional[str],
    valuation_status: str,
    refusal_reason: Optional[str] = None,
) -> UiState:
    """The one state that applies, in a fixed precedence.

    Order matters and is deliberate. Suspension and staleness are checked
    before anything about the model, because a UI must not present research on
    a suspended issuer as current merely because the mathematics succeeded.
    """
    if coverage_status == "SUSPENDED" or research_status == str(
            ResearchStatus.MODEL_SUSPENDED):
        return UiState.SUSPENDED
    if research_status == str(ResearchStatus.STALE):
        return UiState.STALE
    if not model_family or coverage_status == "ONBOARDING":
        return UiState.ONBOARDING
    if valuation_status == "VALUED":
        return UiState.FULL_RESEARCH
    if refusal_reason in DATA_SHORTFALL_REASONS:
        return UiState.PARTIAL
    return UiState.MODEL_UNDER_VALIDATION


def derive_for(document: dict) -> UiState:
    """The state for a built document. The form callers actually use."""
    valuation = document.get("valuation") or {}
    return derive(
        coverage_status=(document.get("coverage") or {}).get("coverageStatus"),
        research_status=str(document.get("researchStatus")),
        model_family=(document.get("company") or {}).get("modelFamily"),
        valuation_status=str(valuation.get("status")),
        refusal_reason=valuation.get("reason"),
    )


# ---------------------------------------------------------------------------
# how each state is reached
# ---------------------------------------------------------------------------


def _rename(document: dict, ticker: str) -> dict:
    document["ticker"] = ticker
    return document


def _onboarding(document: dict) -> dict:
    """No model family maps to this classification — Stage 1's ONBOARDING."""
    document["identity"]["modelFamily"] = None
    document["identity"]["coverageStatus"] = "ONBOARDING"
    document["identity"]["industryCode"] = "UNCLASSIFIED"
    document["identity"]["industryName"] = "Unclassified"
    return document


def _suspended(document: dict) -> dict:
    document["identity"]["coverageStatus"] = "SUSPENDED"
    return document


def _stale(document: dict) -> dict:
    """Every fact published long enough ago to cross the staleness threshold."""
    for fact in document["facts"]:
        if fact.get("publishedAt"):
            fact["publishedAt"] = "2023-03-15T09:00:00Z"
        if fact.get("retrievedAt"):
            fact["retrievedAt"] = "2023-03-15T09:30:00Z"
    return document


#: The metrics a PARTIAL issuer has. Chosen to mirror what Stage 1 actually
#: collects today for a real bank — an equity line and a profit line and
#: nothing else — so the fixture demonstrates the real coverage gap rather than
#: an invented one.
_PARTIAL_METRICS = ("equity_attributable_to_parent",
                    "net_profit_attributable_to_parent")


def _partial(document: dict) -> dict:
    document["facts"] = [
        fact for fact in document["facts"]
        if fact["metric"] in _PARTIAL_METRICS
    ]
    document["quality"]["completeness"] = 1.0
    return document


@dataclass(frozen=True)
class UiStateCase:
    """One UI state, and exactly what it takes to reach it."""

    state: UiState
    ticker: str
    allow_synthetic: bool
    mutate: Optional[Callable[[dict], dict]]
    purpose: str

    @property
    def filename(self) -> str:
        return f"{self.state}.json"


#: The six states, in the order the README and the handoff document them.
UI_STATE_CASES: Tuple[UiStateCase, ...] = (
    UiStateCase(
        state=UiState.FULL_RESEARCH, ticker="SYNB", allow_synthetic=True,
        mutate=None,
        purpose="A complete valuation with the full research package. The only "
                "case that carries a value, and the only one permitted to use "
                "the SYNTHETIC discount rate.",
    ),
    UiStateCase(
        state=UiState.MODEL_UNDER_VALIDATION, ticker="SYNM",
        allow_synthetic=False, mutate=None,
        purpose="Complete data, but no validated risk-free input. The model "
                "ran and refused on methodology rather than on coverage — the "
                "state every real issuer would reach once its facts arrive.",
    ),
    UiStateCase(
        state=UiState.ONBOARDING, ticker="SYNO", allow_synthetic=False,
        mutate=_onboarding,
        purpose="Identity known, no model family mapped. Nothing to value, and "
                "nothing missing either.",
    ),
    UiStateCase(
        state=UiState.STALE, ticker="SYNS", allow_synthetic=False,
        mutate=_stale,
        purpose="Inputs older than the configured threshold. The figures are "
                "still real; what changed is how much weight they carry.",
    ),
    UiStateCase(
        state=UiState.SUSPENDED, ticker="SYNX", allow_synthetic=False,
        mutate=_suspended,
        purpose="Coverage withdrawn by Stage 1. Checked before anything about "
                "the model, so a suspended issuer can never render as current.",
    ),
    UiStateCase(
        state=UiState.PARTIAL, ticker="SYNP", allow_synthetic=False,
        mutate=_partial,
        purpose="A model family applies and two of seventeen required metrics "
                "exist. The state every real Stage 1 issuer is in today.",
    ),
)

#: Every ticker these fixtures use. Asserted absent from the IDX30 universe and
#: from the published data tree.
FIXTURE_TICKERS: Tuple[str, ...] = tuple(c.ticker for c in UI_STATE_CASES)

#: Pinned so regeneration is byte-identical. A wall-clock stamp here would make
#: every regeneration a diff, which would make the "regenerate and compare"
#: test unable to tell drift from the passage of time.
FIXTURE_CALCULATED_AT = "2026-08-05T00:00:00Z"
FIXTURE_AS_OF = "2026-07-31"


# ---------------------------------------------------------------------------
# generation
# ---------------------------------------------------------------------------


def fixtures_dir(settings: EngineSettings) -> Path:
    return settings.fixtures_dir / "ui_states"


def source_document(settings: EngineSettings) -> dict:
    path = settings.fixtures_dir / "synthetic-bank" / "SYNB.json"
    return json.loads(path.read_text(encoding="utf-8"))


def prepare_sandbox(root: Path, repo_root: Path) -> EngineSettings:
    """A throwaway tree with real config and schemas and no output.

    The generator writes input snapshots, so it cannot run against the
    repository: an input snapshot deposited in ``data/`` would be
    indistinguishable from one Stage 1 produced.
    """
    (root / "config").mkdir(parents=True, exist_ok=True)
    (root / "schemas").mkdir(parents=True, exist_ok=True)
    shutil.copytree(repo_root / "config" / "goh-dip-tong",
                    root / "config" / "goh-dip-tong", dirs_exist_ok=True)
    shutil.copytree(repo_root / "schemas" / "goh-dip-tong",
                    root / "schemas" / "goh-dip-tong", dirs_exist_ok=True)
    data = root / "data" / "goh-dip-tong"
    for sub in ("research-snapshots/sample", "research-snapshots/current",
                "financial-facts/annual", "financial-facts/quarterly",
                "financial-statements/restated", "macro"):
        (data / sub).mkdir(parents=True, exist_ok=True)
    return EngineSettings(pipeline=PipelineSettings(repo_root=root))


def build_case(settings: EngineSettings, case: UiStateCase, source: dict) -> dict:
    """Run the engine over one mutated input and return the document.

    Imported lazily so this module can be read for its case table — by a test,
    or by the acceptance script — without pulling in the whole model stack.
    """
    from ..contracts.model import ModelContext
    from ..inputs import loader
    from ..models.registry import model_for
    from ..valuation.guards import load_guards
    from . import snapshot as snapshot_mod
    from .. import MODEL_VERSION

    document = _rename(copy.deepcopy(source), case.ticker)
    if case.mutate is not None:
        document = case.mutate(document)
    (settings.input_snapshots / f"{case.ticker}.json").write_text(
        json.dumps(document, indent=2, sort_keys=True), encoding="utf-8")

    engine_input = loader.load(
        settings, case.ticker, as_of=FIXTURE_AS_OF,
        model_version=MODEL_VERSION, calculated_at=FIXTURE_CALCULATED_AT)

    config = settings.engine_config()
    terminal = config.get("terminal") or {}
    gates = config.get("gates") or {}
    context = ModelContext(
        models_config=settings.pipeline.models(),
        allow_synthetic_cost_of_equity=case.allow_synthetic,
        min_annual_periods=int(gates.get("min_annual_periods", 3)),
        max_input_age_days=gates.get("max_input_age_days"),
        cost_of_capital_config=settings.cost_of_capital(),
        scenario_config=settings.scenarios(),
        persistence=float(terminal.get("persistence", 0.6)),
        guards=load_guards(config),
        model_version=MODEL_VERSION,
        calculated_at=FIXTURE_CALCULATED_AT,
    )
    model = model_for(context.models_config,
                      engine_input.identity.get("modelFamily"))
    return snapshot_mod.build(settings, engine_input, model, context,
                              FIXTURE_CALCULATED_AT)


def build_all(settings: EngineSettings, source: dict) -> Dict[str, dict]:
    """Every fixture document, keyed by state. Deterministic order."""
    return {str(case.state): build_case(settings, case, source)
            for case in UI_STATE_CASES}


def write_all(repo_root: Path, sandbox_root: Path) -> List[Path]:
    """Regenerate the six fixtures into the engine's fixture directory."""
    real = EngineSettings(pipeline=PipelineSettings(repo_root=repo_root))
    sandbox = prepare_sandbox(sandbox_root, repo_root)
    source = source_document(real)

    target = fixtures_dir(real)
    target.mkdir(parents=True, exist_ok=True)

    written: List[Path] = []
    for case in UI_STATE_CASES:
        document = build_case(sandbox, case, source)
        path = target / case.filename
        path.write_text(
            json.dumps(document, indent=2, sort_keys=True, allow_nan=False),
            encoding="utf-8")
        written.append(path)
    return written


def serialise(document: dict) -> str:
    """The exact on-disk form, so a test can compare without re-deriving it."""
    return json.dumps(document, indent=2, sort_keys=True, allow_nan=False)


__all__ = [
    "UiStateCase",
    "UI_STATE_CASES",
    "FIXTURE_TICKERS",
    "FIXTURE_CALCULATED_AT",
    "FIXTURE_AS_OF",
    "DATA_SHORTFALL_REASONS",
    "derive",
    "derive_for",
    "fixtures_dir",
    "source_document",
    "prepare_sandbox",
    "build_case",
    "build_all",
    "write_all",
    "serialise",
]
